version: '3'

services:
  residents-service:
    build: services/residents
    volumes:
      - ./services/residents:/usr/src/app
    ports:
      - 5000:80

  skill:
    build: skill
    volumes:
      - ./skill:/usr/src/app
      -  /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 5003:443

    depends_on:
      - residents-service

  website:
    build: website
    volumes:
      - ./website:/usr/src/app
    ports:
      - 5001:3000
    
    depends_on:
      - residents-service
    