version: '3'

services:
  residents-service:
    build: services/residents
    volumes:
      - ./services/residents:/usr/src/app
    ports:
      - 5000:80

  website:
    build: website
    volumes:
      - ./website:/usr/src/app
    ports:
      - 5001:3000
    
    depends_on:
      - residents-service